import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

type LinkCardProps = {
  name: string;
  link: string;
  description: string;
};
function LinkCard({ link, name, description }: LinkCardProps) {
  return (
    <div className={styles.card}>
      <div className={styles.cardName}>
        <h2 className={styles.h2}>
          <Link
            href={`/${name.toLocaleLowerCase()}?direct=${encodeURIComponent(
              link
            )}`}
          >
            {name}
          </Link>
        </h2>
        <button
          className={styles.cardBtn}
          onClick={() => {
            navigator.clipboard.writeText(
              window.location.host + "/" + name.toLocaleLowerCase()
            );
            alert("Copied url to your clipboard.");
          }}
        >
          📋
        </button>
      </div>
      <p>{description}</p>
    </div>
  );
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>A collection of links to my stuff</h1>

        <div className={styles.grid}>
          <LinkCard
            name="BotExtended"
            link="https://github.com/nearhuscarl/botextended"
            description="A SFD script that adds a ton of bots and weapons"
          />
          <LinkCard
            name="BotExtended"
            link="https://github.com/nearhuscarl/botextended"
            description="A SFD script that adds a ton of bots and weapons"
          />
          <LinkCard
            name="BotExtended"
            link="https://github.com/nearhuscarl/botextended"
            description="A SFD script that adds a ton of bots and weapons"
          />
          <LinkCard
            name="BotExtended"
            link="https://github.com/nearhuscarl/botextended"
            description="A SFD script that adds a ton of bots and weapons"
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
